title: Jacob Bass
description: Adaptive Technologist | Data Analyst
baseurl: ""
url: https://ja-cob.github.io

theme: cvless

# site settings
taglong: I do a lot of things
tagshort: 

# author settings
author:
  name: Jacob Bass
  email: Jacob@caprawave.com
photo: assets/files/portrait.jpg

# social media links
social:
  github: ja-cob
  linkedin: jacobaaronbass
# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
