# WhatATheme
markdown: kramdown
domain: ja-cob.github.io
# URL of the Site
url: 'https://ja-cob.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jacob Bass
# Description of the Site
description: Data Scientist | Python Developer
# URL of Image of the Site
#site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
#favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/bg.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jbass0435@gmail.com
#facebook_username: thedevslot
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: jacobaaronbass
github_username:  ja-cob
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
kaggle_username: jacobbass

# Google Analytics
#google-analytics: 

# Disqus
#disqus-shortname: 

# Name of the Author
author-name: Jacob Bass
# URL for the Image of the Author
author-image: /assets/images/headshot.jpg
# 60 Words About the Author
author-about: Currently seeking opportunities in tech.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ja-cob

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-seo-tag

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
